receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_size: 1000
    timeout: 1s
    send_batch_max_size: 1500

exporters:
  debug:

  elasticsearch/logstash:
    endpoints: # list of logstash endpoints (or load balancer)
      - http://logstash:8080
    flush:
      interval: 1s
    tls:
      insecure_skip_verify: true
    # organize output fields similar to filebeat
    mapping:
      mode: ecs
    # required for es_bulk codec in logstash
    headers:
      Content-Type: application/x-ndjson

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, elasticsearch/logstash]